version: '3.7'

networks:
  mynet:
    external: true

services:

  cadvisor:
    image: registry.datacommand.co.kr/cadvisor:HEAD
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - mynet
    deploy:
      mode: global